"""Run the Dash benchmark dashboard."""

from __future__ import annotations

import argparse
from pathlib import Path

from pdm.dashboard import create_dash_app


def parse_args() -> argparse.Namespace:
    """Parse command-line arguments."""
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--results",
        type=Path,
        default=None,
        help="Optional CSV generated by scripts/evaluate_subsets.py.",
    )
    parser.add_argument("--host", default="127.0.0.1")
    parser.add_argument("--port", type=int, default=8050)
    parser.add_argument("--debug", action="store_true")
    return parser.parse_args()


def main() -> None:
    """Start the dashboard development server."""
    args = parse_args()
    app = create_dash_app(args.results)
    app.run(host=args.host, port=args.port, debug=args.debug)


if __name__ == "__main__":
    main()
